### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by CaiWang0503** [rcedgar/muscle#23]
dyld: Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm
  Referenced from: /Users/wang/src/BLCA/muscle
  Expected in: /usr/local/lib/libstdc++.6.dylib
 in /Users/wang/src/BLCA/muscle
Abort trap: 6

anyone knows how fix it? thank you

**Comment by rcedgar** [comment]
which o/s? which version exactly, did you get the binary from release tag v5,1 or did you recompile?

**Comment by CaiWang0503** [comment]
my mac is macos sierra 10.12.6, i download the muscle5.1.macos_intel64 and then give it execute permissions

**Comment by rcedgar** [comment]
If you recompile it should work. Unfortunately, Apple make it very difficult to build a binary which will run under different MacOS releases, and it's also difficult for me to test on a range of different MacOS releases because accessing Macs in the cloud is clunky and expensive. If anyone has suggestions for improvements, I would be grateful. See the Wiki [https://github.com/rcedgar/muscle/wiki](https://github.com/rcedgar/muscle/wiki) for notes on how and why the Makefile is designed.

**Comment by CaiWang0503** [comment]
thank you very much, i will try gcc-11 and recompile it, and go back here.

**Comment by rcedgar** [comment]
Please trying the installing gcc-11and check if this solves the problem with the `muscle5.1.macos_intel64` binary in the release without recompiling, no doubt other people will have the same problem. Let me know if that is a fix, thanks!

**Comment by CaiWang0503** [comment]
finally, i update the macos to 10.15, and then install gcc-11, and recompile it, it works
