### ISSUE TITLE
*** Error in `muscle': double free or corruption (out): 0x00007ffdb8176090 ***

### ISSUE THREAD

**Issue by Wendy361** [rcedgar/muscle#57]
Hi I got the following error message when I use the CRISPRCasFinder, which includes MUSCLE as an integrated software. How can I fix this issue?
![image](https://user-images.githubusercontent.com/54411033/234616690-144e0938-ce0c-4e40-8981-29fd8b22a5e6.png)

**Comment by rcedgar** [comment]
These sequences are not suitable for MSA by muscle or any other algorithm, they are far too long and are surely not globally alignable. Please open an issue with the authors of CRISPRCasFinder to figure out if this is really a muscle issue, and if so capture the input sequences file and muscle command line so that I can reproduce the problem.

**Comment by Wendy361** [comment]
Hi, thank you for your response. I think that CRISPRCasFinder first use Prodigal to extract the coding sequences from the input FASTA file, followed by aligning the extracted sequences using Muscle. I already open an issue in CRISPRCasFinder https://github.com/dcouvin/CRISPRCasFinder/issues/45

**Comment by Wendy361** [comment]
Hi thank you for your anwswer. The error was gone when I used a fasta file containing shorter sequences from Illumina. The previous one is the Nanopore long sequence fasta.
