### ISSUE TITLE
segmentation fault muscle -align testing.fa -output alignment.afa

### ISSUE THREAD

**Issue by m-leitman** [rcedgar/muscle#76]
When I run the align command for two sequences, I get this error: 

muscle 5.1.osxarm64 [ef62d8-dirty]  17.2Gb RAM, 8 cores
Built Jan 15 2022 11:59:50
(C) Copyright 2004-2021 Robert C. Edgar.
https://drive5.com

Input: 2 seqs, length avg 32604 max 33281

WARNING: Sequence length >5k may require excessive memory

00:00 12Mb    100.0% Derep 1 uniques, 0 dupes
00:00 14Mb    100.0% UCLUST 2 seqs EE<0.01, 1 centroids, 0 members
00:00 14Mb   CPU has 8 cores, running 8 threads                   
zsh: segmentation fault  muscle -super5 testing.fa -output alignment.afa

Does my device not have enough RAM to do this?

**Comment by rcedgar** [comment]
Yes, as the warning message says.

**Comment by chingciripit** [comment]
I am using muscle 3 and always get this error message. Tried it with only 17 protein sequences in fasta format

filtered_sequences_WP_only 17 seqs, max length 13477, avg  length 2937
00:00:00      2 MB(0%)  Iter   1  100.00%  K-mer dist pass 1
00:00:00      2 MB(0%)  Iter   1  100.00%  K-mer dist pass 2
00:00:10    168 MB(1%)  Iter   1  100.00%  Align node
00:00:10    168 MB(1%)  Iter   1  100.00%  Root alignment
00:00:18    181 MB(1%)  Iter   2  100.00%  Refine tree
00:00:18    182 MB(1%)  Iter   2  100.00%  Root alignment
00:00:18    182 MB(1%)  Iter   2  100.00%  Root alignment
zsh: segmentation fault  muscle3 -in  -out Refine biparts

Is it because the variation in the length of the protein sequences too large?

**Comment by rcedgar** [comment]
13477 is probably too long.
